name: CI CD

on:
  push:
    branches: 
      - test
  release:
    types: 
      - released
      - prereleased



jobs:
  build-test:
    if: github.event == 'push' && github.ref == 'refs/head/test'
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: Echo
        run: echo "Testing"
      
      
    
