name: CI CD

on:
  push:
    branches: 
      - test
  release:
    types: 
      - released
      - prereleased



jobs:
  initial:
    runs-on: ubuntu-latest
    steps:
      - name: Output
        run: |
          echo "${{github.event}}"
          echo "${{github.ref}}"
          echo "${{github.ref_name}}"

  build-test:
    needs: initial
    if: github.event == 'push' && github.ref == 'refs/head/test'
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: Echo
        run: echo "Testing"
      
      
    
